name: Temp test-spec-up-t-installer-1
on:
  workflow_dispatch:  # Allows manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: temp-test-spec-up-t-installer-1

      - name: Run Spec-Up-T Installer
        run: |
          cd ..
          node start.js
